### ISSUE TITLE
How to reduce vertical space between minipage?

### ISSUE THREAD

**Issue by AslanDevbrat** [sddevelopment-be/DojiCV#2]

**Comment by stijn-dejongh** [comment]
@AslanDevbrat Sorry to reply after more than a year. I had not received a notification.

You can reduce the vertical space by:
- using the `\vspace{xxxxx}` directive and either providing a negative value to move the page up, or by replacing the existing value by a smaller number.

Similarly, you can reduce the horizontal space between minipages by:
 - changing the minipages width, which is defined here: `\begin{minipage}[t]{0.12\textwidth}`
 - use the `\hspace{xxxx}` directive and either providing a negative value to move the page to the left, or by replacing the existing value by a smaller number.
 
 I hope this helps out anyone who stumbles on this question in the future.
